### PR TITLE
sidebar bug fixed

### LINKED ISSUE #48: Shopping cart (sidebar) is being open when items quantity is changed or items are removed
There is a small bug in the shopping cart page. When some item is removed or the quantity is changed, the sidebar will be opened (and it should not)

### PR DESCRIPTION
**Pull request by yani-c**
closes mrplum/plum_cart#48

### CODE REVIEW

File: src/components/Sidebar/Sidebar.tsx [hunk 1]
```diff
@@ -65,13 +65,29 @@ const Sidebar = forwardRef(
...
       history.push("/shoppingcart");
       close();
     }, [history]);
 
     useEffect(() => {
-      setX(0);
+      document.addEventListener("click", handleClickAddProduct);
+
+      return () => {
+        document.removeEventListener("mousedown", handleClickAddProduct);
```
Comment (luuchorocha) [inline src/components/Sidebar/Sidebar.tsx:89]: The event name given is wrong, it is not the same of the line 86.

**Review by luuchorocha — CHANGES_REQUESTED** [review]

**Review by luuchorocha — APPROVED** [review]
