### PR TITLE
Fix build

### LINKED ISSUE #28: Fix TypeScript compilation
Currently we have a lot of errors:
```
src/App.tsx:59:13 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Readonly<RouteProps>): Route<RouteProps>', gave the following error.
    Type 'ComponentClass<Pick<RouteComponentProps<any, StaticContext, unknown>, never>, any> & WithRouterStatics<({ location }: PropsWithChildren<RouteComponentProps<any, StaticContext, unknown>>) => Element>' is not assignable to type '((props: RouteComponentProps<any, StaticContext, unknown>) => ReactNode) | undefined'.
      Type 'ComponentClass<Pick<RouteComponentProps<any, StaticContext, unknown>, never>, any> & WithRouterStatics<({ location }: PropsWithChildren<RouteComponentProps<any, StaticContext, unknown>>) => Element>' is not assignable to type '(props: RouteComponentProps<any, StaticContext, unknown>) => ReactNode'.
        Type 'ComponentClass<Pick<RouteComponentProps<any, StaticContext, unknown>, never>, any> & WithRouterStatics<({ location }: PropsWithChildren<RouteComponentProps<any, StaticContext, unknown>>) => Element>' provides no match for the signature '(props: RouteComponentProps<any, StaticContext, unknown>): ReactNode'.
  Overload 2 of 2, '(props: RouteProps, context?: any): Route<RouteProps>', gave the following error.
    Type 'ComponentClass<Pick<RouteComponentProps<any, StaticContext, unknown>, never>, any> & WithRouterStatics<({ location }: PropsWithChildren<RouteComponentProps<any, StaticContext, unknown>>) => Element>' is not assignable to type '((props: RouteComponentProps<any, StaticContext, unknown>) => ReactNode) | undefined'.
      Type 'ComponentClass<Pick<RouteComponentProps<any, StaticContext, unknown>, never>, any> & WithRouterStatics<({ location }: PropsWithChildren<RouteComponentProps<any, StaticContext, unknown>>) => Element>' is not assignable to type '(props: RouteComponentProps<any, StaticContext, unknown>) => ReactNode'.

59             render={withRouter(({ location }) => (
               ~~~~~~

  node_modules/@types/react-router/index.d.ts:89:5
    89     render?: (props: RouteComponentProps<any>) => React.ReactNode;
           ~~~~~~
    The expected type comes from property 'render' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Route<RouteProps>> & Readonly<RouteProps> & Readonly<...>'
  node_modules/@types/react-router/index.d.ts:89:5
    89     render?: (props: RouteComponentProps<any>) => React.ReactNode;
           ~~~~~~
    The expected type comes from property 'render' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Route<RouteProps>> & Readonly<RouteProps> & Readonly<...>'

src/App.tsx:60:30 - error TS2571: Object is of type 'unknown'.

60               <Product data={location.state.data} />
                                ~~~~~~~~~~~~~~

src/components/Button/Button.tsx:3:24 - error TS7016: Could not find a declaration file for module 'classnames'. '/home/lucho/projects/plum_cart/node_modules/classnames/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/classnames` if it exists or add a new declaration (.d.ts) file containing `declare module 'classnames';`

3 import classNames from "classnames";
                         ~~~~~~~~~~~~

src/components/Card/Card.tsx:4:24 - error TS7016: Could not find a declaration file for module 'classnames'. '/home/lucho/projects/plum_cart/node_modules/classnames/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/classnames` if it exists or add a new declaration (.d.ts) file containing `declare module 'classnames';`

4 import classNames from "classnames";
                         ~~~~~~~~~~~~

src/components/Card/Card.tsx:35:23 - error TS7006: Parameter 'e' implicitly has an 'any' type.

35   const addProduct = (e) => {
                         ~

src/components/Card/Card.tsx:46:21 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

46       <ProductImage img={img} />
                       ~~~

  src/components/Card/Card.tsx:11:34
    11 const ProductImage = ({ img }: { img: string }): JSX.Element => {
                                        ~~~
    The expected type comes from property 'img' which is declared here on type 'IntrinsicAttributes & { img: string; }'

src/components/List/ImageList.tsx:14:26 - error TS7006: Parameter 'e' implicitly has an 'any' type.

14   const addProductAux = (e) => {
                            ~

src/components/List/ShoppingCartList.tsx:20:24 - error TS2339: Property 'unit_price' does not exist on type 'never'.

20       total += list[i].unit_price * list[i].quantity;
                          ~~~~~~~~~~

src/components/List/ShoppingCartList.tsx:20:45 - error TS2339: Property 'quantity' does not exist on type 'never'.

20       total += list[i].unit_price * list[i].quantity;
                                               ~~~~~~~~

src/components/List/ShoppingCartList.tsx:35:28 - error TS2339: Property 'id' does not exist on type 'never'.

35               key={product.id}
                              ~~

src/components/List/ShoppingCartList.tsx:36:27 - error TS2339: Property 'id' does not exist on type 'never'.

36               id={product.id}
                             ~~

src/components/List/ShoppingCartList.tsx:37:20 - error TS2532: Object is possibly 'undefined'.

37               img={datajson.find((e) => e.id === product.id).img}
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/List/ShoppingCartList.tsx:37:58 - error TS2339: Property 'id' does not exist on type 'never'.

37               img={datajson.find((e) => e.id === product.id).img}
                                                            ~~

src/components/List/ShoppingCartList.tsx:38:30 - error TS2339: Property 'title' does not exist on type 'never'.

38               title={product.title}
                                ~~~~~

src/components/List/ShoppingCartList.tsx:39:35 - error TS2339: Property 'unit_price' does not exist on type 'never'.

39               unit_price={product.unit_price}
                                     ~~~~~~~~~~

src/components/List/ShoppingCartList.tsx:40:33 - error TS2339: Property 'quantity' does not exist on type 'never'.

40               quantity={product.quantity}
                                   ~~~~~~~~

src/components/Mercadopago/Mercadopago.tsx:3:25 - error TS7016: Could not find a declaration file for module 'mercadopago'. '/home/lucho/projects/plum_cart/node_modules/mercadopago/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mercadopago` if it exists or add a new declaration (.d.ts) file containing `declare module 'mercadopago';`

3 import mercadopago from 'mercadopago';
                          ~~~~~~~~~~~~~

src/components/Mercadopago/Mercadopago.tsx:53:19 - error TS2345: Argument of type 'null' is not assignable to parameter of type 'string | undefined'.

53       window.open(pathname);
                     ~~~~~~~~

src/components/Product/Product.tsx:53:13 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(props: { href: string; } & { color?: "inherit" | "default" | "primary" | "secondary" | undefined; disableFocusRipple?: boolean | undefined; edge?: false | "end" | "start" | undefined; size?: "small" | ... 1 more ... | undefined; } & { ...; } & CommonProps<...> & Pick<...>): Element', gave the following error.
    Type '(event: React.ChangeEvent) => void' is not assignable to type '(event: MouseEvent<HTMLAnchorElement, MouseEvent>) => void'.
      Types of parameters 'event' and 'event' are incompatible.
        Type 'MouseEvent<HTMLAnchorElement, MouseEvent>' is not assignable to type 'ChangeEvent<Element>'.
          Types of property 'target' are incompatible.
            Type 'EventTarget' is not assignable to type 'EventTarget & Element'.
              Type 'EventTarget' is missing the following properties from type 'Element': assignedSlot, attributes, classList, className, and 120 more.
  Overload 2 of 3, '(props: { component: ElementType<any>; } & { color?: "inherit" | "default" | "primary" | "secondary" | undefined; disableFocusRipple?: boolean | undefined; edge?: false | "end" | "start" | undefined; size?: "small" | ... 1 more ... | undefined; } & { ...; } & CommonProps<...> & Pick<...>): Element', gave the following error.
    Property 'component' is missing in type '{ children: Element[]; "aria-label": string; color: "default"; onClick: (event: ChangeEvent<Element>) => void; }' but required in type '{ component: ElementType<any>; }'.
  Overload 3 of 3, '(props: DefaultComponentProps<ExtendButtonBaseTypeMap<IconButtonTypeMap<{}, "button">>>): Element', gave the following error.
    Type '(event: React.ChangeEvent) => void' is not assignable to type '(event: MouseEvent<HTMLButtonElement, MouseEvent>) => void'.
      Types of parameters 'event' and 'event' are incompatible.
        Type 'MouseEvent<HTMLButtonElement, MouseEvent>' is not assignable to type 'ChangeEvent<Element>'.
          Types of property 'target' are incompatible.
            Type 'EventTarget' is not assignable to type 'EventTarget & Element'.
              Type 'EventTarget' is not assignable to type 'Element'.

 53             <IconButton
                ~~~~~~~~~~~
 54               aria-label={`star ${data.title}`}
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 56               onClick={addProductAux}
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 57             >
    ~~~~~~~~~~~~~

  node_modules/@types/react/index.d.ts:1455:9
    1455         onClick?: MouseEventHandler<T>;
                 ~~~~~~~
    The expected type comes from property 'onClick' which is declared here on type 'IntrinsicAttributes & { href: string; } & { color?: "inherit" | "default" | "primary" | "secondary" | undefined; disableFocusRipple?: boolean | undefined; edge?: false | ... 2 more ... | undefined; size?: "small" | ... 1 more ... | undefined; } & { ...; } & CommonProps<...> & Pick<...>'
  node_modules/@material-ui/core/OverridableComponent.d.ts:17:7
    17       component: C;
             ~~~~~~~~~
    'component' is declared here.
  node_modules/@types/react/index.d.ts:1455:9
    1455         onClick?: MouseEventHandler<T>;
                 ~~~~~~~
    The expected type comes from property 'onClick' which is declared here on type 'IntrinsicAttributes & { color?: "inherit" | "default" | "primary" | "secondary" | undefined; disableFocusRipple?: boolean | undefined; edge?: false | "end" | "start" | undefined; size?: "small" | ... 1 more ... | undefined; } & { ...; } & CommonProps<...> & Pick<...>'

src/components/SelectButton/SelectButton.tsx:53:11 - error TS2322: Type '(event: React.ChangeEvent<{    value: string;}>) => void' is not assignable to type '(event: ChangeEvent<{ name?: string | undefined; value: unknown; }>, child: ReactNode) => void'.
  Types of parameters 'event' and 'event' are incompatible.
    Type 'ChangeEvent<{ name?: string | undefined; value: unknown; }>' is not assignable to type 'ChangeEvent<{ value: string; }>'.
      Type '{ name?: string | undefined; value: unknown; }' is not assignable to type '{ value: string; }'.
        Types of property 'value' are incompatible.
          Type 'unknown' is not assignable to type 'string'.

53           onChange={handleChange}
             ~~~~~~~~

  node_modules/@material-ui/core/Select/Select.d.ts:84:3
    84   onChange?: SelectInputProps['onChange'];
         ~~~~~~~~
    The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & SelectProps'

src/components/ShippingForm/ShippingForm.tsx:29:21 - error TS7006: Parameter 'e' implicitly has an 'any' type.

29   const onSubmit = (e) => {
                       ~

src/components/ShippingForm/ShippingForm.tsx:34:21 - error TS7006: Parameter 'e' implicitly has an 'any' type.

34   const onChange = (e) => {
                       ~

src/components/Sidebar/Sidebar.tsx:43:31 - error TS7006: Parameter 'event' implicitly has an 'any' type.

43   const handleClickOutside = (event) => {
                                 ~~~~~

src/components/Sidebar/Sidebar.tsx:44:25 - error TS2531: Object is possibly 'null'.

44     if (ref.current && !ref.current.contains(event.target)) {
                           ~~~~~~~~~~~

src/components/Sidebar/Sidebar.tsx:49:27 - error TS7006: Parameter 'event' implicitly has an 'any' type.

49   const handleKeypress = (event) => {
                             ~~~~~

src/context/CartContext.tsx:33:42 - error TS2532: Object is possibly 'undefined'.

33   return { newList: newList, qtyDeleted: deleted.quantity };
                                            ~~~~~~~

src/context/CartContext.tsx:36:18 - error TS7006: Parameter 'state' implicitly has an 'any' type.

36 const reducer = (state, action) => {
                    ~~~~~

src/context/CartContext.tsx:36:25 - error TS7006: Parameter 'action' implicitly has an 'any' type.

36 const reducer = (state, action) => {
                           ~~~~~~

src/context/CartContext.tsx:60:27 - error TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.
  Type 'null' is not assignable to type 'string'.

60   const list = JSON.parse(localStorage.getItem("shoppingcart"));
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/context/CartContext.tsx:74:36 - error TS2322: Type '{ list: IProductShoppingCart[]; quantity: any; }' is not assignable to type '{ list: never[]; quantity: number; }'.
  Types of property 'list' are incompatible.
    Type 'IProductShoppingCart[]' is not assignable to type 'never[]'.
      Type 'IProductShoppingCart' is not assignable to type 'never'.

74     <CartContext.Provider value={{ state, dispatch }}>
                                      ~~~~~

  src/context/defaultValues.tsx:10:3
    10   state: {
         ~~~~~~~~
    11     list: [],
       ~~~~~~~~~~~~~
    12     quantity: 0,
       ~~~~~~~~~~~~~~~~
    13   },
       ~~~
    The expected type comes from property 'state' which is declared here on type '{ state: { list: never[]; quantity: number; }; dispatch: (args: unknown) => void; }'

src/context/LanguageContext.tsx:26:31 - error TS2322: Type '{ languages: string[]; locale: string; toggleLocale: (locale: string) => void; }' is not assignable to type '{ languages: never[]; locale: string; toggleLocale: (locale: string) => void; }'.
  Types of property 'languages' are incompatible.
    Type 'string[]' is not assignable to type 'never[]'.
      Type 'string' is not assignable to type 'never'.

26     <LanguageContext.Provider value={state}>
                                 ~~~~~

  node_modules/@types/react/index.d.ts:337:9
    337         value: T;
                ~~~~~
    The expected type comes from property 'value' which is declared here on type 'IntrinsicAttributes & ProviderProps<{ languages: never[]; locale: string; toggleLocale: (locale: string) => void; }>'

src/utils/Products.ts:1:1 - error TS1208: 'Products.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.

1 
  


Found 32 errors.

```

### PR DESCRIPTION
**Pull request by luuchorocha**
Closes #28 

There is a staging environment running at:
https://plum-cart.herokuapp.com/

### CODE REVIEW

File: src/context/defaultValues.tsx [hunk 1]
```diff
@@ -28,8 +31,8 @@ const defaultUserValue = {
     number: "",
     floor: "",
   },
-  dispatch: (args: unknown): void => {
-    args = args;
+  dispatch: ({ type, payload }: UserAction): void => {
+    console.log(type, payload);
```
Comment (EriGoldenberg) [inline src/context/defaultValues.tsx:35]: console.log(type, payload);

Comment (luuchorocha) [reply src/context/defaultValues.tsx:35]: I added this line to keep eslint happy. If I keep the function empty or I don't use the function parameters, eslint will thrown warnings about that. However, this function will be overridden later so this code should not be executed at any time.

**Review by yani-c — APPROVED** [review]
